### ISSUE TITLE
Questions regarding the login inputs

### ISSUE THREAD

**Issue by sn3fru** [JSSolutions/meteor-google-prediction#1]
thank you for taking the package.

I'm having trouble making authentification. The google console provides .json file and not one .pem file.

Your package is just to login with OAuth2.0 or server-server too? this e-mail service on the login inputs is the email service or users?

Best regards

**Comment by trsdln** [comment]
@sn3fru This package supports only server-server authentication. It is build on top of `google-oauth-jwt` npm package. Here's detailed instruction how to generate .pem file: https://www.npmjs.com/package/google-oauth-jwt#creating-a-service-account-using-the-google-developers-console

**Comment by sn3fru** [comment]
@trsdln thanks for answering.

I generated the p12 file and turned in .pem, put the email that is in json the option email client and the project name. but unfortunately it does not work :(

The id of the project and the method name (trained) it extracts the .pem?

**Comment by trsdln** [comment]
@sn3fru Looks like you used wrong email. You should use email that was generated within certificate you used.
